### ISSUE TITLE
Enhancement Request: Start tunnel via Tasker

### ISSUE THREAD

**Issue by txyaloo** [kaaass/ZerotierFix#18] opened 2022-08-07 22:22 UTC
Would it be possible to add a hook so tasker can start/restart the Zerotier connection based on a set of conditions similar to how it can fire off an OpenVPN or Wireguard connection?

This would be extremely helpful to enable ZT when leaving home network and disable when returning home.

**Comment by kaaass** [comment] 2022-08-08 03:52
Thanks for your advice.

This seems like a duplicate of #9. The implementation of this feature is scheduled and will be tracked in that issue.

**Closed** 2022-08-08 03:52 UTC
Labels: duplicate
